[general]
theme = "dark"
primaryColor = "#F39C12"
backgroundColor = "#2C3E50"
font = "sans serif"

[server]
enableCORS = false
port = 8501

[global]
# This section can be used for global settings if needed in the future.